yolo_model:

  config_file:
    name: yolov3-tiny-urban.cfg
  weight_file:
    name: yolov3-tiny-urban-3_2500.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - person
      - backpack
      - phone
      - drill
      - extinguisher
      - ingress
      - multirotor
      - ugv
      - vertical_shaft
      - vent
      - stairs_up
      - stairs_down
      - railing_flat
      - railing_angle
      - rope
      - helmet

