yolo_model:

  config_file:
    name: ignition_sim_extended.cfg
  weight_file:
    name: ignition_sim_extended_4800.weights
  threshold:
    value: 0.25
  detection_classes:
    names:
      - person
      - backpack
      - phone
      - drill
      - extinguisher
      - ingress
      - multirotor
      - ugv
      - vertical_shaft
